### ISSUE TITLE
FPS Issues

### ISSUE THREAD

**Issue by chrheg** [gnwl/NotGrid#17]
In the lates version I get major FPS issues ( 10-20FPS in 40man raid ) , If i go back to a previous build its almost fine.

**Comment by gnwl** [comment]
I noticed this myself tonight. I'm looking into it. It's to do with aura checking and gets exponentially worse for every buff/debuff a player has. I'm not surprised since I changed a lot of things to OnUpdate but not sure why symptoms weren't there before. I'm going to push an update that will remove aura checking for the time being.

**Comment by gnwl** [comment]
I've rewritten it. Kind of went back to the way it was done way back on the first release. That does mean we might get back to some weird situations of certain auras not fading or showing depending on certain circumstances, but it seems to be pretty good from the testing I've done. I'll keep this issue open for a while.
