### ISSUE TITLE
FPS Issue

### ISSUE THREAD

**Issue by semaphore101** [gnwl/NotGrid#30]
I get like <20 fps when this addon is enabled and in a BG or a Raid (basically anything that utilizes the raid frame display via notgrid), i tried turning off healcomm and other settings but nothing helped.

Any suggestions would be appreciated.

**Comment by gnwl** [comment]
My initial thought would be turn off map proximity and see what that does, but if you've tried disabling everything in options you've prob tried that too.

In that case open frames.lua and change 

`self:UNIT_PROXIMITY(this)` to `--self:UNIT_PROXIMITY(this)` like the line above it. 

Save it and reload your game. Anything that uses the OnUpdate call is subject to cause some significant issues, as it runs on every frame refresh. But not doing that causes a UI that looks unresponsive. I used to do auras on update and that massively killed the fps, but proximity seems fine for me.

I'm curious to know the outcome. I'm not playing on Turtle at the moment and just doing my current testing on a local server. A 40 bot raid killing some trash in MC occasionally dips my fps for a split second but otherwise its a smooth 60. Definitely not a consistent frame reduction.,

**Comment by semaphore101** [comment]
thanks for the reply,
disabling unit_proximity within the onUpdate function fixed the issue!

**Comment by gnwl** [comment]
added a rate limiter for proximity checking. Hopefully will allow you to use proximity without fps issues. Just disabling that function call results in odd behavior as spells and combat logs would still be messing with the unit frames. will likely add a complete disable at some point.
