### ISSUE TITLE
Mouseover healing for pets incorrectly shows like I am healing myself

### ISSUE THREAD

**Issue by DBFBlackbull** [gnwl/NotGrid#38]
I managed to get pets to show up and I can also heal them using the mouseovermacro /ngcast, but the predictive healing does not seem to work for pets.

When I try to heal a pet it looks like I am about to heal myself. It shows the guess for the amount healed on my name plate and the green bar showing how much that is going to fill me up.
Once the heal actually goes off it does heal the pet, which is correct behaviour but it is contradictory to what the UI tells me.

Is there any way to fix this?

**Comment by gnwl** [comment]
I can't seem to recreate this in the way that you're describing. The only way I can make a spellcast appear on myself rather than the expected target is by having autoselfcast toggled. That, however, applies to all units, not just pets, and also goes through with the spellcast onto self.

The heal amount will never work on pets because Healcomm avoids recognizing non-player units. Likely to avoid conflicts with pets having identical names or party/raid members. So that's a bug I can't/won't fix.

**Comment by DBFBlackbull** [comment]
Thank you for the answer. I completely understand.
