### ISSUE TITLE
Feature request? Show icon when missing buffs

### ISSUE THREAD

**Issue by w0lf3h** [gnwl/NotGrid#41]
Not sure if there is already a way to do this with the current options...
Is there an option / would we be able to get an option to display icons on missing buffs? Thanks.

**Comment by gnwl** [comment]
I'm unsure of what this specifically proposes. You just want the  inverse of what it is now?  Where now the icon will show when a unit has  the tracked buff, you want the icon to show when the unit does _not_ have the tracked buff?

**Comment by gnwl** [comment]
Added. The first version I pushed inverted the literal tracking and would be cool to be able to track if _not all_ spirit/fort/shadow present then show the icon. Hide if _all_ those buffs are present. But there was a caveat with equivalent buffs. You wouldn't be able to add Prayer of Fort along with Power Word: Fort because then its checking for the presence of both, not either or. Considered some workarounds for that, but ultimately the compromise is just inverting the show/hide of the icon.
